<!DOCTYPE html>
<html>
<head>
<meta charset="ISO-8859-1">
<style type="text/css">
pre {
  font-family:Courier New;
  font-size:10pt;
}

.af_line {
  color: gray;
  text-decoration: none;
}

</style>
<title>Source file</title>
</head>
<body>
<pre><span style="font-weight:bold;color:#7f7f7f;">diff --git a/day_01_part_1.rb b/day_01_part_2.rb</span>
<span style="font-weight:bold;color:#7f7f7f;">index 1219b40..448b5ff 100644</span>
<span style="font-weight:bold;color:#7f7f7f;">--- a/day_01_part_1.rb</span>
<span style="font-weight:bold;color:#7f7f7f;">+++ b/day_01_part_2.rb</span>
<span style="color:#00cdcd;">&#64;&#64; -1,6 +1,15 &#64;&#64;</span>
input = File.read(&quot;../inputs/day01.txt&quot;).lines.map(&amp;:to_i)

<span style="color:#cd0000;">fuel</span><span style="color:#00cd00;">mass_to_fuel</span> = <span style="color:#cd0000;">input.map</span><span style="color:#00cd00;">-&gt; (mass)</span> {
  <span style="color:#cd0000;">|mass|</span><span style="color:#00cd00;">fuel_mass =</span> mass.div(3) - 2
  <span style="color:#cd0000;">}.reduce(&amp;:+)</span><span style="color:#00cd00;">if fuel_mass &gt; 0</span>
<span style="color:#00cd00;">    fuel_mass + mass_to_fuel[fuel_mass]</span>
<span style="color:#00cd00;">  else</span>
<span style="color:#00cd00;">    0</span>
<span style="color:#00cd00;">  end</span>
<span style="color:#00cd00;">}</span>

<span style="color:#00cd00;">fuel = input.map(&amp;mass_to_fuel).reduce(&amp;:+)</span>

#--
puts &quot;Day 01 - Part <span style="color:#cd0000;">1:</span><span style="color:#00cd00;">2:</span> #{fuel}&quot;
</pre>
</body>
</html>
<!--HTML generated by ansifilter 2.15, http://www.andre-simon.de/-->
